version: '3.8'
services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "3000"
    environment:
      - GENERIC_TIMEZONE=Europe/Zurich
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=christianlipp@icloud.com
      - N8N_BASIC_AUTH_PASSWORD=hEcgyk-tegba7-vucgev
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
